levis:
  name: "nginx"
  deployment:
    containers:
      image: "nginx"
      port: 80
      volumeMounts:
      - name: test-volume
        mountPath: /test-ebs
        readOnly: true
        secretName: test
      - name: oam-volume
        mountPath: /oam-ebs
        readOnly: true
        configName: oam
      - name: em-volume
        mountPath: /em/oam.txt
        subPath: oam.txt
        readOnly: true
    node:
      selector:
        mode: prefer
        operator: In
        labels:
          Nodepool: stateless
      allower:
      - effect: NoSchedule
        operator: In
        StatelessOnly: true
      - effect: NoExecute
        operator: Equal
        Kai: Ped

  service:
    enabled: false